// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiY48tMczX6Wr2wjyRHKtTbGlALHe2xy4',
    appId: '1:172585672145:web:f54428cb807fc8e9f494f0',
    messagingSenderId: '172585672145',
    projectId: 'portfolio-74048',
    authDomain: 'portfolio-74048.firebaseapp.com',
    storageBucket: 'portfolio-74048.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Ubw9UNDXK7Hi7f9hLK6Xgr0iKdP4xxM',
    appId: '1:172585672145:android:69b9dcd81b39f31ef494f0',
    messagingSenderId: '172585672145',
    projectId: 'portfolio-74048',
    storageBucket: 'portfolio-74048.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRAQFC2Ta32lmqijP1Eyn5ngIxXuOUr4c',
    appId: '1:172585672145:ios:9ae12382d07e162ff494f0',
    messagingSenderId: '172585672145',
    projectId: 'portfolio-74048',
    storageBucket: 'portfolio-74048.appspot.com',
    iosClientId: '172585672145-mkmpligh2tkkmc7gc2hf6ncu1rckmajg.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioGilmar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRAQFC2Ta32lmqijP1Eyn5ngIxXuOUr4c',
    appId: '1:172585672145:ios:9ae12382d07e162ff494f0',
    messagingSenderId: '172585672145',
    projectId: 'portfolio-74048',
    storageBucket: 'portfolio-74048.appspot.com',
    iosClientId: '172585672145-mkmpligh2tkkmc7gc2hf6ncu1rckmajg.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioGilmar',
  );
}
